[workspace]
members = [
    "fsm/",
    "fsm_codegen/",
    "fsm_tests/",
    "fsm_timers_std/"
]

[patch.crates-io]
#packed_struct = { path="./packed_struct" }
#packed_struct_codegen = { path="./packed_struct_codegen" }
