//! A runtime description of the FSM's structure: its regions, states, transitions and timers.
//! Generated by the procedural macro for every FSM when the `meta` feature is enabled. Used by
//! the inspection frontends and for the documentation, see [`plantuml::to_plantuml`].
//!
//! The `type_name` fields are the values of [`core::any::type_name`] for the declared types, the
//! same names that the [`Inspect`](crate::Inspect) hooks see, so the inspection events can be
//! matched to the parts of the machine.

use alloc::{boxed::Box, string::String, vec::Vec};

pub mod plantuml;

/// Implemented by the code generator for every FSM.
pub trait FsmMeta {
    /// The description of the machine, including its sub-machines.
    fn fsm_info() -> FsmInfo;
}

/// A state machine.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct FsmInfo {
    /// The name of the FSM's type, without the generics.
    pub id: String,
    pub type_name: String,
    pub context_type_name: String,
    pub regions: Vec<RegionInfo>
}

/// An orthogonal region of the machine, with its own current state.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct RegionInfo {
    pub region_id: usize,
    /// The id of the state that the region enters on start.
    pub initial_state: String,
    pub states: Vec<StateInfo>,
    pub transitions: Vec<TransitionInfo>
}

#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct StateInfo {
    /// The name of the state's type, without the generics. Also the name of the variant in the
    /// FSM's current state enum.
    pub id: String,
    pub type_name: String,
    /// The name of the state's field in the FSM's states struct.
    pub storage_field: String,
    pub timers: Vec<TimerInfo>,
    /// Set when this state is a sub-machine.
    pub sub_machine: Option<Box<FsmInfo>>
}

#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct TimerInfo {
    /// The name of the timer's type, also the variant of the FSM's timers enum.
    pub id: String,
    pub type_name: String
}

#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct TransitionInfo {
    /// The name of the generated (or hinted) transition type.
    pub id: String,
    pub type_name: String,
    pub event: EventInfo,
    pub kind: TransitionKindInfo,
    pub has_guard: bool,
    pub has_action: bool
}

#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(tag = "kind"))]
pub enum EventInfo {
    /// The machine is started.
    Start,
    /// The machine is stopped.
    Stop,
    Event {
        id: String,
        type_name: String
    }
}

impl EventInfo {
    /// A short label of the event.
    pub fn label(&self) -> &str {
        match self {
            EventInfo::Start => "Start",
            EventInfo::Stop => "Stop",
            EventInfo::Event { id, .. } => id
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(feature = "serde", serde(tag = "kind"))]
pub enum TransitionKindInfo {
    /// From one state to another. `None` is the stopped machine: the transition that enters the
    /// initial state has no `from` state.
    Normal {
        from: Option<String>,
        to: Option<String>
    },
    /// Exits and re-enters the state.
    SelfTransition {
        state: String
    },
    /// Handles the event without leaving the state.
    Internal {
        state: String
    }
}
