[package]
name = "finny_derive"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
description = "Procedural macros crate for the main finite state machine crate, finny."
license.workspace = true
keywords = ["fsm", "state"]

[lib]
proc-macro = true

[features]
default = ["std"]
std = []
generate_plantuml = []

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
petgraph.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
