[package]
name = "finny_tests"
version = "0.1.0"
authors.workspace = true
publish = false
edition.workspace = true

[dependencies]
finny = { workspace = true, features = ["async"] }
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "time", "sync", "test-util"] }
