[package]
name = "finny"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
description = "Finite State Machines with a procedural builder-style API and compile time transition checks."
license.workspace = true
keywords = ["fsm", "state", "state-machine"]
categories = ["data-structures", "algorithms", "rust-patterns", "no-std"]
readme = "../README.md"

[dependencies]
derive_more.workspace = true
finny_derive.workspace = true
arraydeque.workspace = true
slog = { workspace = true, optional = true }
heapless.workspace = true

[features]
default = ["std", "inspect_slog", "timers_std"]
std = ["arraydeque/std", "timers_std", "slog/std", "finny_derive/std"]
inspect_slog = ["slog"]
timers_std = []
generate_plantuml = ["finny_derive/generate_plantuml"]
