[package]
name = "fsm_derive"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[dependencies]
quote = "1.0"
syn =  { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"

[lib]
proc-macro = true

